# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  tsmworklogsapi:
    image: tsmworklogsapi
    build:
      context: .
      dockerfile: src/TSM.WorkLogs.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5253:5253
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
